services:
  jaeger:
      image: jaegertracing/all-in-one:1.55
      container_name: jaeger
      ports:
        - "16686:16686"   # UI
        - "6831:6831/udp" # Agent
        - "6832:6832/udp" # Collector (UDP)
        - "14268:14268"   # HTTP collector
      networks:
        - txn-processor-network
networks:
  txn-processor-network:
    name: txn-processor-network